server:
  port: 5090
  host: 0.0.0.0

db:
  host: host.docker.internal
  port: 5432
  user: sitchi
  password: change_me_prod_password
  dbname: sitchi
  sslmode: disable

auth:
  jwt_secret: "change_me_prod_secret"
  access_token_ttl_minutes: 60
  refresh_token_ttl_minutes: 120960
  issuer: "sitchi"

dev: false
